version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: 
         name: build update
         command: |
           sudo apt-get update
           echo "Successfully Build"
      # Add your build commands here
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
         name: run test
         command: python3 hello.py # Add your test command here
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: 
         name: run deployment 
         command: echo "Successfully Deploy"
      # Add your deployment commands here

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - main
      - build:
          filters:
            branches:
              only:
                - feature
      - deploy:
          filters:
            branches:
              only:
                - main



