version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9  # Choose an appropriate Docker image with your desired environment.
    steps:
      - checkout  # Check out the code from the repository
      - run:
          name: Run tests
          command: python3 hello.py  # Replace with the command to run your tests
 
workflows:
  version: 2
  feature-branch-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main  # Replace "feature-branch" with your actual feature branch name

