version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9  # Choose an appropriate Docker image with your desired environment.
    steps:
      - checkout  # Check out the code from the repository
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      - run:
          name: Run tests
          command: python3 hello.py  # Replace with the command to run your tests

  create-pull-request:
    docker:
      - image: circleci/python:3.9  # Choose an appropriate Docker image with your desired environment.
    steps:
      - checkout  # Check out the code from the repository
      - run:
          name: Create Pull Request
          command: |
            git fetch origin pull/$CIRCLE_PULL_REQUEST/merge:pr-merge
            git checkout pr-merge
            git rebase main
            git push origin pr-merge:$CIRCLE_BRANCH  # Push changes to the remote branch as a PR

workflows:
  version: 2
  build-and-deploy-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - feature  # Replace "feature-branch" with your actual feature branch name
      - create-pull-request:
          requires:
            - build
          filters:
            branches:
              only:
                - feature  # Replace "feature-branch" with your actual feature branch name

