version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9  # Choose an appropriate Docker image with your desired environment.
    steps:
      - checkout  # Check out the code from the repository
      - run:
          name: Run tests
          command: python3 hello.py  # Replace with the command to run your tests

  push-to-main:
    docker:
      - image: circleci/python:3.9  # Choose an appropriate Docker image with your desired environment.
    steps:
      - checkout  # Check out the code from the repository
      - run:
          name: Push changes to main
          command: |
            git checkout main  # Switch to the main branch
            git merge $CIRCLE_BRANCH  # Merge the feature branch into main
            git push origin main  # Push changes to the remote main branch

workflows:
  version: 2
  build-and-push-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - feature  # Replace "feature-branch" with your actual feature branch name
      - push-to-main:
          requires:
            - build
          filters:
            branches:
              only:
                - feature  # Replace "feature-branch" with your actual feature branch name


