version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: 
         name: build update
         command: |
           sudo apt-get update
           echo "Successfully Build"
      # Add your build commands here
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
         name: run test
         command: python3 hello.py # Add your test command here
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: 
         name: run deployment 
         command: echo "Successfully Deploy"
      # Add your deployment commands here
# https://circleci.com/developer/orbs/orb/circleci/terraform
version: '2.1'
orbs:
  terraform: circleci/terraform@1.2.1
workflows:
  version: 2
  test_build_deploy:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - feature
      - terraform/validate:
        checkout: true
        context: terraform
      - terraform/plan:
        checkout: true
        context: terraform
        persist-workspace: true
        requires:
        - terraform/validate
        
      - build:
          filters:
            branches:
              only:
                - feature
                
      - deploy:
          filters:
            branches:
              only:
                - main
      - terraform/apply:
        attach-workspace: true
        context: terraform
        filters:
          branches:
            only: main
        requires:
        - terraform/plan



