version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:latest  # Replace with the appropriate Docker image for your project
    steps:
      - checkout
      - run: python3 hello.py # Add your test commands here
  build:
    docker:
      - image: circleci/node:latest  # Replace with the appropriate Docker image for your project
    steps:
      - checkout
      - run: echo "Building..."
      # Add your build commands here
  deploy:
    docker:
      - image: circleci/node:latest  # Replace with the appropriate Docker image for your project
    steps:
      - checkout
      - run: echo "Deploying..."
      # Add your deployment commands here

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - main
      - build:
          filters:
            branches:
              only:
                - develop
      - deploy:
          filters:
            branches:
              only:
                - main



